language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
notifications:
  slack:
    secure: gi56H28OmqwWiT76HtiP54KAa6yxLgREgDUkeuwNmHRBWWpHHaRhryGxhCcgse1NwsgIsbspqgBrJBQ7nBdYQyyZYBI6KfGvudNU5vhZQbtWWaGyI/uxE6LNZhMj+wUStS+E8OIg3IREJbKcTOwMoLl7ct5P2KyCW8/69Zu8rlq732Gk/X7dsP9SaaU3UCes//HIRyAUD1m4oN2ROYEW4Nc1BjCPnEBBecp8RJ8yhvqR3X+nFFkTiBnman3ACmN/3bhD1LAA4E0jtfXwHvtH4zoySXo9KIqWq/liBQ6Zy4ynGz89IOVy71w3qwuYK5DcvgM/dm3s6oklGxMEJlAdDsfnln2AKd5mlbeuKFdyw7muuBHGGgWz0Rn2MoXzxRNZmK2JRMousE5e2E9OZkDZFT57PXo2JuzT6aRVkDST3NjIsYa/2w/IbD3KbrigW0BXu5+et1nzjxdJ+54EpsV83MIDc7w+4NcwF6dVR1k71ocTR6iKYl3lKq7BRFyHG75LLkG1Vd3gp/wlsSSc8cTOSuLzGEhV5yDHQ/y7LSHN81r7yeZQtyh9U3GwyxZOChdcXMAVUwT6KqDz0DbmpvXLMykJw2Of2S+DXTONKVm90rQyE8uDxpGdtAAGB/cQAN2tETQbrqmlaYkaCuOg7SFdRW8rAQ/wjo2lFuUmJQkklR8=
